name: Deploy PyDay to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout código
      
    - uses: actions/setup-node@v4
      name: Setup Node.js 22.x
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Instalar dependencias y build
      run: |
        npm ci
        npm run build
        
    - name: Copia archivos hacia servidor
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.PYDAY_SERVER }}
        username: ${{ secrets.PYDAY_USER }}
        password: ${{ secrets.PYDAY_PASS }}
        port: ${{ secrets.PYDAY_PORT }}
        source: ".next,public,next.config.mjs,package.json,package-lock.json"
        target: "pydaydotcl"
        
    - name: Iniciar app con PM2 en el servidor
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.PYDAY_SERVER }}
        username: ${{ secrets.PYDAY_USER }}
        password: ${{ secrets.PYDAY_PASS }}
        port: ${{ secrets.PYDAY_PORT }}
        script: |
          cd pydaydotcl
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 22
          npm install --omit=dev
          pm2 delete pydaydotcl || true
          pm2 start npm --name "pydaydotcl" -- start
